jobs:
  - name: daily
    schedule: 0 12 * * * # Define when this job should run, using cron format.
    steps:
      - name: run models
        command: dbt run
      - name: test models
        command: dbt test

  - name: weekdays
    schedule: 30 7 * * 1-5 # The example will run every weekday at 7:30am.
    steps:
      - name: run models
        command: dbt run
